### ISSUE TITLE
External database, cannot connect

### ISSUE THREAD

**Issue by marvelloard** [Kedu-SCCL/docker-koha-community#1]
Setting the correct variables for an external MySQL database results in "*** Database server still down. Waiting 3 seconds until retry". I can however reach the DB server from within the container using the correct host, port, username variable (+password) just fine.
I assume some set variables aren't being correctly used by the entrypoint.sh script, but I'm not sure.

**Comment by keducoop** [comment]
Thanks for reporting, we will have a look, but I'm afraid it will not be very soon....

Meanwhile it will be useful if you provide steps to reproduce the issue, If possible providing exact environment variable settings.

**Comment by marvelloard** [comment]
I see, thank you.

**Comment by keducoop** [comment]
No news from reporter (@marvelloard ), so closing the issue
